CREATE SEQUENCE seq_AUTORES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_LIBROS START WITH 1 INCREMENT BY 1;


CREATE TABLE AUTORES (
id INT PRIMARY KEY,
nombre VARCHAR(100) NOT NULL,
apellido VARCHAR(100) NOT NULL,
nacionalidad VARCHAR(50),
fecha_nacimiento DATE
);

CREATE TABLE LIBROS (
id INT PRIMARY KEY,
titulo VARCHAR (200) NOT NULL,
isbn VARCHAR(20) NOT NULL UNIQUE,
año_publicacion INT,
genero VARCHAR(50),
CONSTRAINT fk_LIBROS_AUTORES FOREIGN KEY (id) REFERENCES AUTORES(id)
)